# fly.toml file generated for augend on 2021-10-24T13:43:54+01:00

app = "augend"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_KEEP_FILES = "media/*:templates/*"


[env]
  AUGEND_PORT = "8080"
  AUGEND_TEMPLATE_DIR = "/workspace/templates"
  AUGEND_MEDIA_DIR = "/workspace/media"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthz/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
